In [24]:
import pandas as pd
import numpy as np
import random

In [33]:
filename = "review.csv"
n = sum(1 for line in open(filename)) - 1 #number of records in file (excludes header)
s = 1000 #desired sample size
skip = sorted(random.sample(range(1,n+1),n-s)) #the 0-indexed header will not be included in the skip list
df = pd.read_csv(filename, skiprows=skip)
sorted_sample = df[df['useful']>0]


In [35]:
#review length (useful>0)
def countWords(text):
    wordCount = [len(text.split(" "))]
    return np.average(wordCount)

avgWords = [countWords(text) for text in sorted_sample.text]
avgWordsCorr = np.corrcoef(avgWords, sorted_sample.useful)
print(avgWordsCorr)

[[1.         0.23762563]
 [0.23762563 1.        ]]


In [36]:
#review length (all data)
def countWords(text):
    wordCount = [len(text.split(" "))]
    return np.average(wordCount)

avgWords = [countWords(text) for text in df.text]
avgWordsCorr = np.corrcoef(avgWords, df.useful)
print(avgWordsCorr)

[[1.         0.35817309]
 [0.35817309 1.        ]]


In [38]:
#stars (useful>0)
starCorr = np.corrcoef(sorted_sample.stars, sorted_sample.useful)
print(starCorr)

[[1.         0.02112049]
 [0.02112049 1.        ]]


In [39]:
#stars (useful>0)
starCorr = np.corrcoef(df.stars, df.useful)
print(starCorr)

[[ 1.         -0.09082658]
 [-0.09082658  1.        ]]
